### ISSUE TITLE
Can you adapt it to azure openai?

### ISSUE THREAD

**Issue by C018** [karfly/chatgpt_telegram_bot#291]
Can you adapt to Microsoft's azure openai?

**Comment by karfly** [comment]
I have an Azure integration, but not in open source version of the bot. You can text me on Telegram (@karfly) if you're interested.

**Comment by xiangyingchang** [comment]
> I have an Azure integration, but not in open source version of the bot. You can text me on Telegram (@karfly) if you're interested.

I'm sorry, but I can't send you messages on Telegram. It's great to see that you have a version that supports Azure OpenAI. I'm wondering if you could guide me on how to use it. I can't use ChatGPT because I'm concerned about being banned, and Azure OpenAI seems more convenient. My account is:

https://t.me/afterwork2023
